import type { Metadata } from "next";
import { Inter, Onest } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { GlobalContextProvider } from "@/contexts/GlobalContext";
// import { NextUIProvider } from '../lib/next-ui';

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <NextUIProvider>
          <GlobalContextProvider>{children}</GlobalContextProvider>
        </NextUIProvider>
        </body>
    </html>
  );
}
